export interface RootObject {
  header: Header;
  hero: Hero;
  homePage: HomePage;
  properties: Properties;
  contact: Contact;
  footer: Footer;
  login: Login;
  searchPage: SearchPage;
  singeProperty: SingeProperty;
}

export interface SingeProperty {
  views: string;
  share: string;
  Favorites: string;
  renovation: string;
  buildingType: string;
  description: string;
  buildingFeatures: string;
  specialProperties: string;
  location: string;
  FavoritesMsg: string;
  date: string;
  id: string;
  shareWith: string;
  copy: string;
  copied: string;
  CopyToClipboard: string;
  close: string;
  numberOfBedrooms: string;
  numberOfBathrooms: string;
  numberOfFloor: string;
  area: string;
  specialProperty: string;
  ApartmentFeatures: string;
  BuildingFeatures: string;
  seeAll: string;
  propertyNotFound: string;
  "We're sorry, but the property you're looking for doesn't exist or has  been removed.": string;
  Refresh: string;
  "m²": "м²";
  Yes: "Да";
  No: "Нет";
  perDay: string;
  perMonth: string;
  price: any;
}

export interface SearchPage {
  buy: string;
  rent: string;
  DailyRent: string;
  sortByDate: string;
  sortByPrice: string;
  apartment: string;
  house: string;
  commercial: string;
  land: string;
  investment: string;
  newConstruction: string;
  byDeveloper: string;
  buildingTypes: string;
  PriceRange: string;
  numberOfRooms: string;
  numberOfFloor: string;
  numberOfBathrooms: string;
  Significance: string;
  floorAreaTitleApartment: string;
  houseArea: string;
  "Land surface (sq/m)": string;
  floor: string;
  province: string;
  distric: string;
  sqMiterRange: string;
  gardenSqMiterRange: string;
  houseSqMiterRange: string;
  renovations: string;
  utilities: string;
  aditionals: string;
  seeMore: string;
  houseType: string;
  resetAll: string;
  applyFilter: string;
  filter: string;
  sortbyDate: string;
  sortbyPrice: string;
  property_not_found: string;
  property_error_message: string;
  nextPage: string;
  prevPage: string;
}

export interface Login {
  singnInTitle: string;
  authMsg: string;
  termsMsg: string;
  termsofService: string;
  privacyPolicy: string;
  and: string;
  email: string;
  emailmessage: string;
  password: string;
  passwordMessage: string;
  forget: string;
  signing: string;
  signin: string;
}
export interface Forget {
  button: string;
  forgetting: string;
  title: string;
  submitting: string;
  emailmessage: string;
  email: string;
}

export interface Footer {
  buy: string;
  rent: string;
  DailyRent: string;
  investment: string;
  privacyPolicy: string;
  login: string;
  logout: string;
  dashboard: string;
}

export interface Contact {
  ContactUsMessage: string;
  fullName: string;
  nameError: string;
  emailError: string;
  phoneError: string;
  nameDesc: string;
  email: string;
  emailDesc: string;
  phone: string;
  phoneDesc: string;
  comment: string;
  commentError: string;
  commentMessage: string;
  optional: string;
  attachFile: string;
  noFileSelected: string;
  send: string;
  sendRequest: string;
}

export interface Properties {
  perMonth: string;
  perDay: string;
  bed: string;
  bathroom: string;
  area: string;
  views: string;
  shares: string;
  likes: string;
  location: string;
  propertyNotFound: string;
  "We're sorry, but the property you're looking for doesn't exist or has  been removed.": string;
  Refresh: string;
}

export interface HomePage {
  bestOffer: string;
  chooseYourType: string;
  apartment: string;
  house: string;
  commercial: string;
  land: string;
  seeMore: string;
}

export interface Hero {
  title: string;
  search: string;
  significance: string;
  buy: string;
  rent: string;
  DailyRent: string;
  apartment: string;
  house: string;
  commercial: string;
  land: string;
  numberOfRooms: string;
  moreFilters: string;
  allTypes: string;
  selected: string;
  province: string;
  distric: string;
  sqMiterRange: string;
}

export interface Header {
  buy: string;
  rent: string;
  DailyRent: string;
  PostAd: string;
  Favorite: string;
  Languages: string;
  currency: string;
  Menu: string;
}

export interface AdminRoot {
  dashboard: Dashboard;
}
export interface Dashboard {
  Dashboard: string;
  MyProperties: string;
  Contacts: string;
  Inbox: string;
  ProfileSettings: string;
  Users: string;
  Branches: string;
  watch: string;
  share: string;
  activeProperties: string;
  allPropertiesViews: string;
  daily: string;
  monthly: string;
  statisticsFor: string;
  logout: string;
  Role: string;
  yearly: string;
  noPropertiesFound: string;
}
export interface AdminProperties {
  all: string;
  buy: string;
  rent: string;
  dailyRent: string;
  draft: string;
  archive: string;
  propertiId: string;
  address: string;
  searchByPropertiId: string;
  searchByAddress: string;
  seeMore: string;
  noPropertiesFound: string;
}

export interface PropertyForm {
  chooseType: string;
  houseType: string;
  Preview: string;
  Cancel: string;
  Delete: string;
  moveToDraft: string;
  pleaseResolveTheErrorsBeforeSovingToDraft: string;
  Validation: string;
  numberOfRooms: string;
  numberOfBathroom: string;
  numberOfFloors: string;
  Renovation: string;
  Furniture: string;
  Utilities: string;
  Additional: string;
  ID: string;
  "Land surface": string;
  sqM: string;
  Address: string;
  Description: string;
  mSquare: string;
  houseSurface: string;
  HouseArea: string;
  monthlyFee: string;
  dailyFee: string;
  price: string;
  enterPrice: string;
  generateCustomId: string;
  writeDescription: string;
  WriteArmDescription: string;
  AddARMDescription: string;
  AddRusDescription: string;
  WriteRusDescription: string;
  AddEnTitle: string;
  WriteEnTitle: string;
  ProvinceStateCity: string;
  WriteEnDescription: string;
  AddEnDescription: string;
  Province: string;
  District: string;
  RewriteTitle: string;
  Title: string;
  AddArmtitle: string;
  WriteRusTitle: string;
  ConstructionType: string;
  BuildingType: string;
  "Floor area sq/m": string;
  floor: string;
  Area: string;
  "House Area": string;
  Significance: string;
  "Cancel Action": string;
  "House type": string;
  "Building type": string;
  "Construction type": string;
  "Do you want to cancel this action or move it to draft?": string;
  "This property already exists in your account.": string;
  "Duplicate Error": string;
  Post: string;
  "Post an Ad": string;
  Back: string;
  "Choose category": string;
  Info: string;
  "title.required": string;
  "description.required": string;
  "price.required": string;
  "location.required": string;
  "images.required": string;
  "details.bathroomRequired": string;
  "details.bedroomRequired": string;
  "details.areaRequired": string;
  "details.totalAreasRequired": string;
  "details.utilityRequired": string;
  "details.amenityRequired": string;
  "details.SignificanceRequired": string;
  "houseType.required": string;
  "buildingType.required": string;
  "ConstructionType.required": string;
  "renovation.required": string;
  "details.zoningTypeRequired": string;
  "details.businessTypeRequired": string;
  "Furniture type is required": string;
  "Property Updated and moved to draft": string;
  "Property Updated successfully": string;
  Success: string;
  Error: string;
  "Fill in": string;
  "Best offer?": string;
  "Drop or upload photo (max": string;
  max: string;
  photos: string;
  "You can only upload up to": string;
  // "Площадь дома (кв/м)": string;
  House: string;
  "Enter type 3/16X format": string;
  Only: string;
  imageUploadError: string;
  isContractBased: string;
}
export interface Inbox {
  noNewMailFound: string;
  all: string;
  new: string;
  date: string;
  name: string;
  email: string;
  propertyId: string;
  phone: string;
  message: string;
}

export interface Profile {
  changePhoto: string;
  AddPhoto: string;
  profile: string;
  changePassword: string;
  fullName: string;
  email: string;
  phoneNumber: string;
  selectMessengersAttachedToThisNumber: string;
  messenger: string;
  viber: string;
  whatsApp: string;
  telegram: string;
  addNewNumber: string;
  cancel: string;
  saveChanges: string;
  oldPassword: string;
  newPassword: string;
  confirmPassword: string;
  error: string;
  thereWasAnProblem: string;
  profileUpdateSuccess: string;
  success: string;
  saveImage: string;
  profileImageUploading: string;
  uploading: string;
  profileUpdatedSuccessfully: string;
  thereWasAnErrorUpdatingYourProfile: string;
  changingPassword: string;
  failedToSetupPassword: string;
  oldPasswordError: string;
  newPasswordError: string;
  confirmPasswordError: string;
  notMatchPassword: string;
  dragAndDrop: string;
  NameIsRequired: string;
  InvalidEmailAddress: string;
  InvalidPhoneNumberFormat: string;
  PhoneNumberIsTooShort: string;
  PhoneNumberIsTooLong: string;
}

export interface Users {
  users: string;
  addNewUser: string;
  noResults: string;
  NAME: string;
  ROLE: string;
  BRANCH: string;
  ACTIVITY: string;
  NoBrowser: string;
  ACTION: string;
  LastLogin: string;
  Browser: string;
  Search: string;
  name: string;
  anUnexpectedErrorOccurred: string;
  Success: string;
  Error: string;
  Avatar: string;
  FirstName: string;
  LastName: string;
  Email: string;
  EmailAddress: string;
  Role: string;
  SelectARole: string;
  Agent: string;
  Manager: string;
  Director: string;
  Branch: string;
  SelectABranch: string;
  NoBranchesFound: string;
  SearchForABranch: string;
  PhoneNumber: string;
  messenger: string;
  viber: string;
  whatsApp: string;
  telegram: string;
  AddNewNumber: string;
  Bio: string;
  description: string;
  AddressAndLocation: string;
  AddLocationAndAddress: string;
  StreetAddress: string;
  Country: string;
  City: string;
  ZipCode: string;
  State: string;
  SaveChanges: string;
  Create: string;
  EditUser: string;
  AddUser: string;
  EditAUser: string;
  AddANewUser: string;
  firstNameError: string;
  lastNameError: string;
  emailError: string;
  bioError: string;
  branchIdError: string;
  streetError: string;
  cityError: string;
  stateError: string;
  zipCodeError: string;
  countryError: string;
  phoneNumberError: string;
  phoneTypeError: string;
  roleError: string;
  FailedToLoadUserDetails: string;
  NoPropertiesFoundForThisUser: string;
  Back: string;
  steet: string;
  AgentDetails: string;
  IdentificationNumber: string;
  PleaseWait: string;
  Deleting: string;
  UserSuccessfullyDeleted: string;
  SomethingWentWrongPleaseTryAgainLater: string;
  ImageSizeLimit: string;
  ImageExceedsSizeLimit: string;
  DropOrUploadPhoto: string;
}
export interface BranchTypes {
  Branches: string;
  BRANCH: string;
  PHONENUMBER: string;
  ADDRESS: string;
  ACTION: string;
  Search: string;
  name: string;
  AddNewBranch: string;
  NoResults: string;
  EditBranch: string;
  SaveChanges: string;
  CreateBranch: string;
  error: string;
  success: string;
  BackToBranch: string;
  CoverImage: string;
  Name: string;
  BranchName: string;
  Email: string;
  EmailAddress: string;
  Phone: string;
  PhoneNumber: string;
  AddressAndLocation: string;
  AddLocationandaddress: string;
  StreetAddress: string;
  City: string;
  State: string;
  ZipCode: string;
  Country: string;
  branchNameError: string;
  coverImageError: string;
  streetError: string;
  cityError: string;
  stateError: string;
  zipCodeError: string;
  countryError: string;
  phoneError: string;
  emailError: string;
  faxError: string;
  websiteError: string;
  Back: string;
  BranchDetails: string;
  IdentificationNumber: string;
  PleaseWait: string;
  Deleting: string;
  BranchSuccessfullyDeleted: string;
  SomethingWentWrongPleaseTryAgainLater: string;
  ImageSizeLimit: string;
  ImageExceedsSizeLimit: string;
  DropOrUploadPhoto: string;
}

export interface SinglePropertyDict {
  "m²": string;
  Back: string;
  Edit: string;
  Duplicate: string;
  Delete: string;
  "Deleted property": string;
  "Deleting....": string;
  "Deleting property....": string;
  Error: string;
  Yes: string;
  No: string;
  "something went wrong while deleting property": string;
  "Are you sure you want to delete? This Action can only be undone": string;
  "Failed to delete property": string;
  "Please wait, Property being duplicated...": string;
  "duplicating...": string;
  Success: string;
  "moving to archive...": string;
  "Please wait, Property moving to archive...": string;
  "moving to unarchive...": string;
  "Please wait, Property moving to unarchive...": string;
  Unarchive: string;
  archive: string;
  "Move to": string;
  "Post an Ad?": string;
  Preview: string;
  "Are you ready to post your advertisement? Please review all details to ensure accuracy.": string;
  Cancel: string;
  "Publishing...": string;
  "Post has been successfully published": string;
  "Please wait, Property being to published...": string;
}
